### PR TITLE
file save/save_as filename correction

### PR DESCRIPTION
**Pull request by pissard**

### CODE REVIEW

**Comment by crocsg** [comment]
Hello Roger,
good proposal, but still a problem
under Windows create_file_dialog strangely return a string, and you are right an array under linux. 
i'll do something

**Comment by crocsg** [comment]
Just push a fix on head of branch main taking account of windows and linux. Just test it under Debian, it seem to work

**Comment by crocsg** [comment]
BTW the current filename display  is missing, when you use "save" you don't know wichh filename you are using :-(

**Comment by crocsg** [comment]
Just waiting your confirmation about the fix before closing the request

**Comment by pissard** [comment]
Hello Stephane,

I confirm that your fix is also ok with my ubuntu version.

Thanks a lot

**Pull request closed without merging**
